# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
opt_out_usage

platform :ios do
    before_all do
        # Make sure we start off with a clean slate
        ensure_git_status_clean
        # sigh
        # sigh(
        #     app_identifier: 'com.dezinezync.Yeti.YetiShare'
        # )
    end

    desc "Push a new beta build to TestFlight"
    lane :beta do
        
        ensure_git_branch(
            branch: 'dev'
        )
        
        increment_build_number(xcodeproj: "Yeti.xcodeproj")
        
        build_app(
            scheme: "Yeti",
            include_bitcode: false,
            include_symbols: true
        )

        upload_to_testflight(
            skip_submission: true,
            skip_waiting_for_build_processing: true
        )

    end
end
