# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
opt_out_usage

platform :ios do
    before_all do
        # Make sure we start off with a clean slate
        ensure_git_status_clean
    end

    desc "Push a new beta build to TestFlight"
    lane :beta do

        # ensure_git_branch(
        #     branch: 'dev'
        # )

        changelog = File.read("../changelog.md")

        increment_build_number(
            xcodeproj: "Yeti.xcodeproj"
        )

        gym(
            include_bitcode: false,
            include_symbols: false,
            configuration: 'Testflight'
        )

        upload_to_testflight(
            skip_submission: true,
            skip_waiting_for_build_processing: false,
            changelog: changelog
        )

    end

    desc "Push a new beta build to AppStore"
    lane :release do

        ensure_git_branch(
            branch: 'master'
        )

        increment_build_number(
            xcodeproj: "Yeti.xcodeproj"
        )

        gym(
            include_bitcode: false,
            include_symbols: false,
            configuration: 'Release'
        )

        pilot(
            skip_submission: true,
            skip_waiting_for_build_processing: true
        )

    end

    after_all do |lane|
        say "done"
        commit_version_bump(
            message: 'Version Bump via Fastlane',
            xcodeproj: 'Yeti.xcodeproj', # optional, if you have multiple Xcode project files, you must specify your main project here
        )

        add_git_tag

        push_to_git_remote
    end

    error do |lane, exception|
        # reset version bumps
        reset_git_repo(
            disregard_gitignore: false
        )
    end
end
